name             'gc-aws'
maintainer       'Zach Schneider'
maintainer_email 'zachschneider@berniesanders.com'
license          'AGLP-3.0'
description      'Installs/Configures gc-aws'
long_description 'Installs/Configures gc-aws'
version          '0.1.0'
depends          'postgresql'
depends          'multicorn'
