name             'gc-aws'
maintainer       'Zach Schneider'
maintainer_email 'zachschneider@berniesanders.com'
license          'AGLP-3.0'
description      'Installs/Configures gc-aws'
version          '0.2.0'
